### PR TITLE
General cleanup | added webpack | added ics export

### PR DESCRIPTION
**Pull request by saibotk**

### CODE REVIEW

**Comment by Miterion** [comment]
Just a short review, but the index.html is never moved to the dist folder, so this does not work according to the README

**Comment by saibotk** [comment]
As it is not needed in the dist folder. I can't see a problem with this, could you elaborate on the problem?

**Comment by Miterion** [comment]
This line fails during execution
https://github.com/d120/beautiful-tucan/blob/06bcb5fcd18b35f14be909a01f7acf0f74e71087/step2.py#L28

**Comment by drcicero** [comment]
Hi! I'm not sure my opinion is needed, and I have never been trained on writing reviews, but:

I see you did some reverse engineering to find out that !w.room.startsWith("Übung ") || selectuebungs[cur.id] === format_weekly(w) are the relevant items. Sorry, that it looks like that. ^^

Note, the ".weekly" is only intended for the weekly overview, so I guess some it might be lossy compared to the actual list of events, e.g. some one-time events with different rooms or different times might be skipped in the weekly overview. Instead of "x.weekly.map(y => y.firstDate times y.count)" the ics should contain the actual dates from "x.dates", which is are the direct raw "date\ttime\troom" from Tucan, + the selected uedate, which can be repeated, because beautiful-tucan does not currently look up all individual ~15 uebungsdates anyway, so repeating them is the same we're currently doing in python.

Regarding "beautifying": The code already was 'beautified', just with a different style guide (2 spaces instead of 1 tab). This switch is orthogonal to adding ics generation, and should not necessarily come in the same pull request.

That aside, I think the cost of adding webpack and npm adds lots of dependencies and I was actually quite proud to completely understand everything about the project until now. On the other hand I can see that ical is hard (i once tried to write an ics parser and generator in lua ^^ did not really work because ics is strange). I do find +4100 lines package lock file not fun.

The .gitignore needlessly blocks lots of files that would never be generated (a much smaller one would be sufficient).

**Comment by saibotk** [comment]
> This line fails during execution
> 
> [beautiful-tucan/step2.py](https://github.com/d120/beautiful-tucan/blob/06bcb5fcd18b35f14be909a01f7acf0f74e71087/step2.py#L28)
> 
> Line 28 in [06bcb5f](/d120/beautiful-tucan/commit/06bcb5fcd18b35f14be909a01f7acf0f74e71087)
>  with open("dist/page.html")  as f: page_tmpl  = f.read()

Should work now. Sorry!

> Note, the ".weekly" is only intended for the weekly overview, so I guess some it might be lossy compared to the actual list of events, e.g. some one-time events with different rooms or different times might be skipped in the weekly overview. Instead of "x.weekly.map(y => y.firstDate times y.count)" the ics should contain the actual dates from "x.dates", which is are the direct raw "date\ttime\troom" from Tucan, + the selected uedate, which can be repeated, because beautiful-tucan does not currently look up all individual ~15 uebungsdates anyway, so repeating them is the same we're currently doing in python.

I will look into that, jeah i just wanted to extract them and this was the first place i found what i needed.

> Regarding "beautifying": The code already was 'beautified', just with a different style guide (2 spaces instead of 1 tab). This switch is orthogonal to adding ics generation, and should not necessarily come in the same pull request.

Thats up to the contributors, but i can remove / change the code style sure, then i would suggest adding a little documentation on the code style that should be used.

> That aside, I think the cost of adding webpack and npm adds lots of dependencies and I was actually quite proud to completely understand everything about the project until now. On the other hand I can see that ical is hard (i once tried to write an ics parser and generator in lua ^^ did not really work because ics is strange). I do find +4100 lines package lock file not fun.

Jeah even finding a good ics package was a pain. And i dont think webpack adds real overhead, since it is only included as a devDependency so it is not included when building the project in production mode. Also having an ics download is a big thing, at least when talkin to my friends / people i know. 

> The .gitignore needlessly blocks lots of files that would never be generated (a much smaller one would be sufficient).

I think that this should not be considered a problem, since its more "future-proof" i'd say. But i'm open for discussion.

I started with just hacking together the ics download for myself, so i can get my calendar up and running :+1:  but then i thought other people may be interested too, so i pushed them to GH and made a PR.

**Comment by drcicero** [comment]
> I started with just hacking together the ics download for myself, so i can get my calendar up and running +1 but then i thought other people may be interested too, so i pushed them to GH and made a PR.

No worries! Everything is a hack! And I am interested in ical support. Cool idea. :smile: 

> ... but i can remove / change the code style sure, then i would suggest adding a little documentation on the code style, that should be used.

I hope it is easy to see that independent of whether there is an explicit style guide, touching more lines than needed, renaming files, moving files, adding files and so on can causes merge conflicts with other changes, and I have some lying around. So I would recommend to apply formatting only to changed code. (Not only in this repo but with every pull request.)

Of course that is hypocrisy, considering I personally like to rename things and move them around and currently everything is undocumented and a hack. Well, at least I did not make any indentation changes recently. :roll_eyes:. I just need to wait until I want my history to be merged back in and then @Miterion can tell me that there lots of merge conflicts and I should have worked cleaner, or something... :)

> Yeah even finding a good ics package was a pain. And i don't think webpack adds real overhead, since it is only included as a devDependency so it is not included when building the project in production mode. Also having an ics download is a big thing, at least when talking to my friends / people i know.

... So, I looked at ics again, and it seems fairly easy to generate without any dependencies, so we can get around having to use npm and webpack or any other build complications, just generating static files and be done with it. I used the following dates, e.g. normal dates from `.dates` and uebungs dates from `.weekly` as described earlier:

~~~js
var calendardates = selected
  .flatMap(module => Object.values(module.content).map(x => [module, x]))
  .flatMap(x => [
    ...x[1].dates
      .map(y => y + "\t" + x[0].title_short),
    ...x[0].weekly
      .filter(w => w.room.startsWith("Übung ")
                && selectuebungs[x[0].id] === format_weekly(w))
      .flatMap(y =>
        [...Array(y.count).keys()].map(i =>
          ical.ymd(new Date(+new Date(y.firstdate) + 1000*60*60*24*7 * i))
        + "\t"+ format_timespan(y).replace(" - ", "\t") +"\t-\tÜbung " + x[0].title_short) )
  ]);
~~~

Would your calendar client accept the ics generated with the button I experimentally added to https://www.student.informatik.tu-darmstadt.de/~dr85nixo/beautiful-tucan/ (right below the calendar view)? I tried ics import to Thunderbird/Lightning with some bachelor courses and it seemed to work. Do you know someone using a different calendar to check whether it works there, too?

**Comment by Miterion** [comment]
> you know someone using a different calendar to check whether it works there, too? 

Can confirm that it works with Google Calendar. I would also prefer if the amount of dependencies is as small as possible.

**Comment by miterion** [comment]
What is the status of this PR @saibotk ?

**Comment by saibotk** [comment]
I decided to rebase on @drcicero master and thus removed the annoying code beautification, but still use webpack to build the site (minification etc), i am now transforming @drcicero's ICS implementation to the ics-generator library, because i do not want to reinvent the wheel and it should also be easier to add / remove features within the calendar, when a lib is used, where everything is already implemented.

Thats the current status

**Comment by miterion** [comment]
Amazing, thanks for all the work :)
Just give me a short ping when you think it is ready to be merged

**Comment by saibotk** [comment]
Seems to work as expected, at least ics generation works, but im not sure, if it wont miss any items.
But the feature itself is implemented and worked for me correctly ( as correct as it can be, with this messy tucan data :D ). 

Feel free to merge @miterion :+1:

**Pull request merged**
